
    #Sparrow Mysql/MariaDB Shard proxy config.
    #example config.

    [global]
    log_path = "/home/xxx/log/"
    #log level: debug/info/warn/error, default error.
    log_level = "debug"
    #only log query which take time > log_slow_query_time ms.
    log_slow_query_time = 100

    [proxy]
    listen_addr = "0.0.0.0:9696"
    charset = "gbk"
    #proxy user auth.
    proxy_users = [

        {user = "root", pwd = "root"},
        {user = "sparrow",pwd = "sparrow"}

    ]

    [web]
    listen_addr = "0.0.0.0:9797"
    web_user = "admin"
    web_pwd = "admin"


    #db  instance list.
    [[db_node_list]]
    id = "mysql_1"
    listen_addr = "0.0.0.0:9797"
    user = "root"
    pwd = "root"
    time_to_no_alive = 100 #ms
    #max_conns_limit = 100
    #---------

    [[db_node_list]]
    id = "mysql_2"
    listen_addr = "0.0.0.0:9798"
    user = "root"
    pwd = "root"
    time_to_no_alive = 100 #ms
    #max_conns_limit = 100
    #---------

    [[db_node_list]]
    id = "mysql_3"
    listen_addr = "0.0.0.0:9799"
    user = "root"
    pwd = "root"
    time_to_no_alive = 100 #ms
    #max_conns_limit = 100
    #---------

    [[db_node_list]]
    id = "mysql_4"
    listen_addr = "0.0.0.0:9897"
    user = "root"
    pwd = "root"
    time_to_no_alive = 100 #ms
    #max_conns_limit = 100
    #---------

    [[db_node_list]]
    id = "mysql_5"
    listen_addr = "0.0.0.0:9997"
    user = "root"
    pwd = "root"
    time_to_no_alive = 100 #ms
    #max_conns_limit = 100
    #---------

    [[db_node_list]]
    id = "mysql_6"
    listen_addr = "0.0.0.0:9899"
    user = "root"
    pwd = "root"
    time_to_no_alive = 100 #ms
    #max_conns_limit = 100
    #---------

    # define mysql cluster list.
    [[db_cluster_list]]
    id = "cluster_1"
    master_node_id = "mysql_1"
    slave_node_id_list= ["mysql_2", "mysql_3"]

    [[db_cluster_list]]
    id = "cluster_2"
    master_node_id = "mysql_4"
    slave_node_id_list  = ["mysql_5", "mysql_6"]

    #define db shard router info for each proxy user.
    #the "owner" which  is a proxy user  name.
    [[db_shard_schema_list]]
    owner = "root"
    db = "test_db"
    table = "hash_table"
    shard_key = "id"
    db_cluster_id_list = ["cluster_1", "cluster_2"]
    default_write_to  = "cluster_1"
    each_cluster_table_split_count = [ 2,7]
    shard_type = "hash"

    #---
    [[db_shard_schema_list]]
    owner = "root"
    db = "sparrow"
    table = "date_day_table"
    shard_key = "date_day"
    db_cluster_id_list = ["cluster_1", "cluster_2"]
    default_write_to = "cluster_1"
    shard_type = "date_day"
     # which means left close and right  close range , such as: [ 20191102, 20201102]
    day_range = [ "2019-11-02", "2020-11-02", "2021-11-02", "2022-11-02"]
    #---
    [[db_shard_schema_list]]
    owner = "root"
    db = "ordinal_db"
    table = "test_table"
    shard_key = "id"
    db_cluster_id_list = ["cluster_1", "cluster_2"]
    default_write_to = "cluster_1"
    each_cluster_table_split_count = [ 3,9]
    shard_type = "ordinal_number "
