
    #Sparrow Mysql/MariaDB Shard proxy config.
    #example config.

    [global]
    log_path = "/home/yjl/log/output.log"
    #log level: error/warn/info/debug/trace, default error.
    log_level = "trace"
    #only log query which take time > log_slow_query_time ms.
    log_slow_query_time = 100

    [proxy]
    listen_addr = "127.0.0.1:9696"
    charset = "utf8"
    time_to_no_alive = 3600
    #proxy user auth.
    users = [

        {user = "root", pwd = "root"},
        {user = "sparrow",pwd = "sparrow"}

    ]

    [web]
    listen_addr = "0.0.0.0:9797"
    web_user = "admin"
    web_pwd = "admin"


    #db  instance list.
    [[node]]
    id = "mysql_1"
    listen_addr = "0.0.0.0:9797"
    user = "root"
    pwd = "root"
    max_conns_limit = 10000
    #---------

    [[node]]
    id = "mysql_2"
    listen_addr = "0.0.0.0:9798"
    user = "root"
    pwd = "root"
    max_conns_limit = 10000
    #---------

    [[node]]
    id = "mysql_3"
    listen_addr = "0.0.0.0:9799"
    user = "root"
    pwd = "root"
    max_conns_limit = 10000
    #---------

    [[node]]
    id = "mysql_4"
    listen_addr = "0.0.0.0:9897"
    user = "root"
    pwd = "root"
    max_conns_limit = 10000
    #---------

    [[node]]
    id = "mysql_5"
    listen_addr = "0.0.0.0:9997"
    user = "root"
    pwd = "root"
    max_conns_limit = 10000
    #---------

    [[node]]
    id = "mysql_6"
    listen_addr = "0.0.0.0:9899"
    user = "root"
    pwd = "root"
    max_conns_limit = 10000
    #---------

    # define mysql cluster list.
    [[cluster]]
    id = "cluster_1"
    master_node_id = "mysql_1"
    slave_node_ids= ["mysql_2", "mysql_3"]

    [[cluster]]
    id = "cluster_2"
    master_node_id = "mysql_4"
    slave_node_ids  = ["mysql_5", "mysql_6"]

    #define db shard schema for every proxy user
    #the "owner" which  is a proxy user  name.
    [[schema]]
    owner = "root"   #Attention: owner of the schema must be unique!!!
    [[schema.db]]
    db = "db1"  #Attention : db name must be unique!!!
    cluster_ids = ["cluster_1", "cluster_2"]
    [[schema.db.table]]
    table = "hash_table"
    shard_key = "id"
    shard_type = "hash"
    each_cluster_table_split_count = [ 2,7]
    [[schema.db.table]]
    table = "person"
    shard_key = "code"
    shard_type = "hash"
    each_cluster_table_split_count = [ 3,10]
    #-----------------
    [[schema.db]]
     db = "db2"
     cluster_ids = ["cluster_1", "cluster_2"]
    [[schema.db.table]]
    table = "ordinal_range_table"
    shard_key = "date_str"
    shard_type = "integer_range"
     # which means left close and right  open range , [start, end), such as: [ 20191102, 20201102)
    integer_range = [ "20191102", "20201102", "20201102", "20221006"]
    each_cluster_table_split_count = [ 8,10]
   [[schema.db.table]]
    table = "integer_table"
    shard_key = "id"
    shard_type = "integer"
    each_cluster_table_split_count = [ 3,9]
  
